spring:
  jpa:
    database: POSTGRESQL
    show:
      sql: true
  datasource:
    platform: postgres
    url: "jdbc:postgresql://192.168.0.109:5432/dvdrental2"
    username: postgres
    password: post123
  database:
    driverClassname: org.postgresql.Driver

management:
  metrics:
    export:
      influx:
        enabled: true
        db: micrometer
        step: 5s
        uri: http://127.0.0.1:8086
  endpoints:
    web:
      exposure:
        include: "*"